import {CampusMobility} from './campusMobility';
import {PelicanCyclist} from './pelicanCyclist';
import {applyNightEmission,makeNightLighting} from './nightLighting';
import {makeConnections} from './connections';
import {makeLakeDucks,swimLakeDucks} from './lakeDucks';
import {teachingEntranceCut} from './teachingEntrance';
import {makeAfterglowSky,makeNightSky,type LightMode} from './lighting';
import {photoViews} from '../data/photoViews';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {areas,buildings,places,toWorld,tourIds,type Area,type Point,type Place} from '../data/campus';
import {pathMesh,mergeScene,disposeTree} from './geometry';
import {makeCampusTerrain,campusTreePoints,campusTreeColours} from './campusModel';
import {woodedHillHeight} from './woodedHill';
type Callbacks={select:(id:string)=>void;ready:()=>void;error:(message:string)=>void;manual:()=>void};
export class CampusScene {
 renderer:T.WebGLRenderer;scene=new T.Scene();camera=new T.PerspectiveCamera(38,1,.8,4500);controls:OrbitControls;root=new T.Group(); terrain=new T.Group(); vegetation=new T.Group();
 private mobility=new CampusMobility();private sky=makeAfterglowSky();private nightSky=makeNightSky();private nightLights=makeNightLighting();private lightMode:LightMode='day';private backdropGround?:T.Mesh;private roseRim=new T.DirectionalLight('#e39ccd',0);
 private dirty=true;private renderedFrames=0;private photoReference:string|null=null;private previousFrame=performance.now();
 private light=new T.DirectionalLight(0xfff3d6,3);private hemi=new T.HemisphereLight(0xddebf0,0xc1bd9c,2.6);private pickers:T.Mesh[]=[];private labels=new Map<string,HTMLElement>();private current?:Place;private raf=0;private disposed=false;private resizeObs:ResizeObserver;private lastLabels=0;private pointer=new T.Vector2();private down=new T.Vector2();private ray=new T.Raycaster();private selectedRing=new T.Group();private planned=new T.Group();private cameraTween?:{from:T.Vector3;to:T.Vector3;targetFrom:T.Vector3;targetTo:T.Vector3;start:number;duration:number};private visibleIds=new Set(places.filter(p=>p.status==='built').map(p=>p.id));private showLabels=true;private viewArea:Area|'all'='all';private drawFrames:number[]=[];private degraded=false;private builtGroups=new Map<Area,T.Group>();private modelStatus:Record<string,string>={};private reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;private readyAt=0;private started=performance.now();private rotateIcon?:HTMLElement;
 constructor(private host:HTMLElement,private labelHost:HTMLElement,private callbacks:Callbacks){
 this.renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));this.renderer.setClearColor('#ecefe6');this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.shadowMap.autoUpdate=false;this.renderer.shadowMap.needsUpdate=true;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.95;host.append(this.renderer.domElement);this.renderer.domElement.setAttribute('aria-label','大学城校园三维地图，使用鼠标或触屏探索');this.renderer.domElement.tabIndex=0;
 this.scene.fog=new T.Fog('#ecefe6',1900,3300);this.scene.add(this.root,this.hemi,this.light);this.light.position.set(-400,800,500);this.light.castShadow=true;this.light.shadow.mapSize.set(2048,2048);Object.assign(this.light.shadow.camera,{left:-700,right:700,top:700,bottom:-700,near:1,far:2200});this.light.shadow.normalBias=1.8;this.light.shadow.bias=-.0002;
 this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.08;this.controls.minDistance=65;this.controls.maxDistance=3200;this.controls.maxPolarAngle=Math.PI*.43;this.controls.screenSpacePanning=false;this.controls.target.set(...this.v3(toWorld([660,649])));this.camera.position.copy(this.controls.target).add(new T.Vector3(850,1040,638));this.controls.update();this.controls.addEventListener('start',this.manual);this.controls.addEventListener('change',()=>{this.dirty=true;});
 this.roseRim.position.set(600,380,-350);this.scene.add(this.roseRim);
 this.root.add(this.terrain,this.vegetation,this.selectedRing,this.planned,this.nightLights,this.mobility.group);this.buildTerrain();this.buildBasic();this.buildTrees();this.createLabels();this.rotateIcon=document.querySelector('.compass-needle')??undefined;
 this.renderer.domElement.addEventListener('pointerdown',this.onDown);this.renderer.domElement.addEventListener('pointerup',this.onUp);this.renderer.domElement.addEventListener('keydown',this.onKey);this.renderer.domElement.addEventListener('webglcontextlost',this.onLost);
 this.resizeObs=new ResizeObserver(()=>this.resize());this.resizeObs.observe(host);this.resize();this.frame();this.readyAt=performance.now();callbacks.ready();this.loadDetails();
 }
 private v3(p:Point):[number,number,number]{return [p[0],0,p[1]];}
 private ducks=makeLakeDucks();private duckTime=0;private pelican=new PelicanCyclist();
 private tourOrbitAt=0;
 stopTour(){this.tourOrbitAt=0;this.controls.autoRotate=false;}
 tourLandmark(id:string){this.focus(id);this.landmarkView('tour');this.tourOrbitAt=performance.now()+1150;}
 private manual=()=>{this.tourOrbitAt=0;this.controls.autoRotate=false;this.cameraTween=undefined;this.callbacks.manual();};
 private onLost=(e:Event)=>{e.preventDefault();this.callbacks.error('三维显示暂时不可用，已切换二维校园图。');};
 private onDown=(e:PointerEvent)=>{this.down.set(e.clientX,e.clientY);};
 private onUp=(e:PointerEvent)=>{if(this.down.distanceTo(new T.Vector2(e.clientX,e.clientY))>6||e.button!==0)return;const r=this.host.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);const hits=this.ray.intersectObjects(this.pickers,false);for(const hit of hits){const ids:string[]=hit.object.userData.ids;const id=ids.find(x=>this.visibleIds.has(x));if(id){this.callbacks.select(id);return;}}};
 private onKey=(e:KeyboardEvent)=>{const shifts:Record<string,Point>={ArrowUp:[0,-15],ArrowDown:[0,15],ArrowLeft:[-15,0],ArrowRight:[15,0]};if(shifts[e.key]){e.preventDefault();this.manual();const [x,z]=shifts[e.key];this.controls.target.add(new T.Vector3(x,0,z));this.camera.position.add(new T.Vector3(x,0,z));}if(e.key==='+'||e.key==='='){e.preventDefault();this.zoom(.85);}if(e.key==='-'){e.preventDefault();this.zoom(1.18);}};
 private resize(){const {clientWidth:w,clientHeight:h}=this.host;if(!w||!h)return;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.dirty=true;}
 private buildTerrain(){
 const plane=new T.Mesh(new T.PlaneGeometry(5000,5000),new T.MeshStandardMaterial({color:'#e9eade',roughness:1}));plane.rotation.x=-Math.PI/2;plane.position.y=-8;plane.receiveShadow=true;this.scene.add(plane);this.backdropGround=plane;
 // Ground, paving, water, roads, park and gates come from the shared
 // headless-safe assembly in campusModel.ts, which the Minecraft exporter also
 // consumes, so the viewer and the export can never diverge.
 this.terrain.add(makeCampusTerrain());
 this.root.add(this.ducks,this.pelican.group);
 const merged=mergeScene(this.terrain);disposeTree(this.terrain);this.terrain.clear();this.terrain.add(merged);merged.traverse(o=>{if(o instanceof T.Mesh)o.castShadow=false;});
 }
 private buildBasic(){for(const area of Object.keys(areas) as Area[]){const group=new T.Group();group.name='district-'+area;this.root.add(group);this.builtGroups.set(area,group);}for(const b of buildings){if(b.kind==='lake')continue;const p=places.find(p=>p.id===b.placeIds[0])!;const [x,z]=toWorld(b.position);
 const hit=new T.Mesh(new T.BoxGeometry(Math.max(b.width,12),Math.max(b.height,4),Math.max(b.depth,10)));hit.position.set(x,Math.max(b.height,4)/2+1,z);hit.rotation.y=b.rotation;hit.updateMatrixWorld();hit.userData.ids=b.placeIds;hit.userData.bounds=new T.Box3().setFromObject(hit);this.pickers.push(hit);
 if(p.status==='planned'){const e=new T.EdgesGeometry(new T.BoxGeometry(b.width,b.height,b.depth));const wire=new T.LineSegments(e,new T.LineDashedMaterial({color:'#a18a65',dashSize:3,gapSize:2}));wire.computeLineDistances();wire.position.set(x,b.height/2+1,z);wire.rotation.y=b.rotation;this.planned.add(wire);continue;}
 const mesh=new T.Mesh(new T.BoxGeometry(b.width,Math.max(b.height,1),b.depth),new T.MeshStandardMaterial({color:b.color}));mesh.position.set(x,b.height/2+1,z);mesh.rotation.y=b.rotation;mesh.castShadow=true;mesh.receiveShadow=true;this.builtGroups.get(p.area)!.add(mesh);
 }this.planned.visible=false;}
 private async loadDetails(){try{const {makeBuilding}=await import('./models');for(const area of Object.keys(areas) as Area[]){await new Promise(r=>setTimeout(r,60));if(this.disposed)return;const local=new T.Group();for(const b of buildings){const p=places.find(p=>p.id===b.placeIds[0])!;if(p.area===area&&p.status==='built')local.add(makeBuilding(b));}local.add(makeConnections(area));const merged=mergeScene(local);disposeTree(local);if(this.disposed){disposeTree(merged);return;}const target=this.builtGroups.get(area)!;disposeTree(target);target.clear();target.add(merged);applyNightEmission(merged,this.lightMode==='night');this.modelStatus[area]='ready';this.renderer.shadowMap.needsUpdate=true;this.dirty=true;} }catch(e){this.modelStatus.error=String(e);this.callbacks.error('部分精细模型未能加载，已保留基础建筑。');}}
 private buildTrees(){
 const points=campusTreePoints();
 const tree=new T.InstancedMesh(new T.IcosahedronGeometry(1,1),new T.MeshStandardMaterial({color:'#ffffff',roughness:1}),points.length);tree.name='campus-trees';const trunk=new T.InstancedMesh(new T.CylinderGeometry(.45,.65,5,5),new T.MeshStandardMaterial({color:'#8f9273'}),points.length);const mat=new T.Matrix4(),q=new T.Quaternion(),colors=campusTreeColours;points.forEach((p,i)=>{mat.compose(new T.Vector3(p.x,woodedHillHeight(p.x,p.z)+5+p.s*.45,p.z),q,new T.Vector3(p.s,p.s*1.05,p.s));tree.setMatrixAt(i,mat);tree.setColorAt(i,new T.Color(colors[Math.floor(p.c*colors.length)]));mat.compose(new T.Vector3(p.x,woodedHillHeight(p.x,p.z)+2.8,p.z),q,new T.Vector3(1,1,1));trunk.setMatrixAt(i,mat);});tree.castShadow=true;tree.receiveShadow=true;this.vegetation.add(tree,trunk);
 }
 private createLabels(){for(const p of places){const el=document.createElement('button');el.className='map-label'+(p.landmark?' landmark':'')+(p.status==='planned'?' planned':'');el.textContent=p.name+(p.status==='planned'?' · 规划':'');el.type='button';el.setAttribute('aria-label','查看'+p.name);el.onclick=()=>this.callbacks.select(p.id);this.labelHost.append(el);this.labels.set(p.id,el);} }
 private layoutLabels(time:number){if(time-this.lastLabels<90)return;this.lastLabels=time;const w=this.host.clientWidth,h=this.host.clientHeight;const distance=this.camera.position.distanceTo(this.controls.target);const rects:{x:number;y:number;w:number;h:number}[]=[];const selected=this.current?.id;const sorted=[...places].sort((a,b)=>Number(b.id===selected)-Number(a.id===selected)||Number(!!b.landmark)-Number(!!a.landmark));let visible=0;
 for(const p of sorted){const el=this.labels.get(p.id)!;el.classList.toggle('selected',p.id===selected);if(!this.visibleIds.has(p.id)||(!this.showLabels&&p.id!==selected)||(!p.landmark&&p.id!==selected&&distance>620)||visible>(distance>850?8:20)){el.style.display='none';continue;}const b=buildings.find(b=>b.id===p.buildingIds[0]);const [x,z]=toWorld(p.position);const world=new T.Vector3(x,(b?.height??0)+8,z);const pt=world.clone().project(this.camera);const px=(pt.x*.5+.5)*w,py=(-pt.y*.5+.5)*h;if(pt.z>1||pt.z<0||px<40||px>w-45||py<40||py>h-95){el.style.display='none';continue;}const rw=Math.max(65,p.name.length*12+20),rh=30;const r={x:px-rw/2,y:py-rh,w:rw,h:rh};if(rects.some(a=>r.x<a.x+a.w+6&&r.x+r.w+6>a.x&&r.y<a.y+a.h+5&&r.y+r.h+5>a.y)){el.style.display='none';continue;}if((py<125&&px<290)||(px>w-76&&py<475)){el.style.display='none';continue;}if(p.id!==selected){const delta=world.clone().sub(this.camera.position),distanceToLabel=delta.length();const ray=new T.Ray(this.camera.position,delta.normalize()),hitPoint=new T.Vector3();if(this.pickers.some(m=>!m.userData.ids.includes(p.id)&&m.userData.ids.some((id:string)=>this.visibleIds.has(id))&&ray.intersectBox(m.userData.bounds,hitPoint)&&hitPoint.distanceTo(this.camera.position)<distanceToLabel-8)){el.style.display='none';continue;}}rects.push(r);el.style.display='block';el.style.transform=`translate(${px}px,${py}px) translate(-50%,-100%)`;visible++;}
 if(this.rotateIcon){const a=this.controls.getAzimuthalAngle();this.rotateIcon.style.transform=`rotate(${-a*180/Math.PI}deg)`;}
 }
 private frame=(time=performance.now())=>{if(this.disposed)return;const delta=Math.min(.1,Math.max(0,(time-this.previousFrame)/1000));this.previousFrame=time;this.raf=requestAnimationFrame(this.frame);if(this.cameraTween){const t=Math.min(1,(time-this.cameraTween.start)/this.cameraTween.duration),s=1-Math.pow(1-t,3);this.camera.position.lerpVectors(this.cameraTween.from,this.cameraTween.to,s);this.controls.target.lerpVectors(this.cameraTween.targetFrom,this.cameraTween.targetTo,s);if(t===1)this.cameraTween=undefined;}this.controls.target.x=T.MathUtils.clamp(this.controls.target.x,-850,850);this.controls.target.z=T.MathUtils.clamp(this.controls.target.z,-850,850);if(!this.photoReference)this.controls.target.y=0;if(this.tourOrbitAt&&time>=this.tourOrbitAt){this.tourOrbitAt=0;this.controls.autoRotate=!this.reduced;this.controls.autoRotateSpeed=1.1;}this.controls.update(delta);this.camera.position.y=Math.max(2.5,this.camera.position.y);
 for(const b of buildings){if(b.height<4||places.find(p=>p.id===b.placeIds[0])?.status==='planned')continue;const [x,z]=toWorld(b.position),dx=this.camera.position.x-x,dz=this.camera.position.z-z,c=Math.cos(b.rotation),sn=Math.sin(b.rotation),lx=dx*c-dz*sn,lz=dx*sn+dz*c;
  const court=b.kind==='teaching'?teachingEntranceCut(b):undefined;
  // The shared open courtyard is not occupied by the old rectangular body.
  // Keep its low photo viewpoints instead of lifting the camera above a roof.
  if(court&&Math.abs(lx-court.x)<court.width/2-1&&Math.abs(lz-court.z)<court.depth/2+7)continue;
  if(Math.abs(lx)<b.width/2+8&&Math.abs(lz)<b.depth/2+8)this.camera.position.y=Math.max(this.camera.position.y,b.height+12);
 }
if(!this.reduced&&!document.hidden){this.duckTime+=delta;swimLakeDucks(this.ducks,this.duckTime);this.dirty=true;}
if(this.mobility.step(delta,!this.reduced&&!document.hidden))this.dirty=true;
if(this.pelican.step(delta,!this.reduced&&!document.hidden))this.dirty=true;
if(this.dirty){this.renderer.render(this.scene,this.camera);this.renderedFrames++;this.dirty=false;}this.layoutLabels(time);this.drawFrames.push(time);if(this.drawFrames.length>120)this.drawFrames.shift();if(!this.degraded&&time-this.started>12000&&this.fps<28){this.applyLowQuality();}};
 private applyLowQuality(){
  this.degraded=true;this.renderer.setPixelRatio(Math.min(devicePixelRatio,.85));this.renderer.shadowMap.enabled=false;
  // Keep all building detail; use simpler diffuse shading and canopy geometry
  // only on devices that cannot sustain the initial quality.
  const converted=new Map<T.Material,T.MeshLambertMaterial>();
  this.root.traverse(o=>{if(!(o instanceof T.Mesh)||Array.isArray(o.material)||!(o.material instanceof T.MeshStandardMaterial))return;const old=o.material;let material=converted.get(old);if(!material){material=new T.MeshLambertMaterial({color:old.color,vertexColors:old.vertexColors,side:old.side,transparent:old.transparent,opacity:old.opacity,emissive:old.emissive,emissiveIntensity:old.emissiveIntensity});converted.set(old,material);}o.material=material;});
  converted.forEach((_,old)=>old.dispose());
  const canopy=this.vegetation.children.find(o=>o.name==='campus-trees') as T.InstancedMesh|undefined;if(canopy){canopy.geometry.dispose();canopy.geometry=new T.IcosahedronGeometry(1,0);}
  this.dirty=true;
 }
 get fps(){const fs=this.drawFrames;return fs.length>1?(fs.length-1)*1000/(fs[fs.length-1]-fs[0]):0;}
 get metrics(){return {fps:Math.round(this.fps),renderedFrames:this.renderedFrames,drawCalls:this.renderer.info.render.calls,triangles:this.renderer.info.render.triangles,geometries:this.renderer.info.memory.geometries,textures:this.renderer.info.memory.textures,readyMs:Math.round(this.readyAt-this.started),models:this.modelStatus,quality:this.degraded?'low':'standard',renderer:this.renderer.getContext().getParameter(this.renderer.getContext().RENDERER)};}
 private move(target:T.Vector3,offset:T.Vector3,instant=false){this.cameraTween=undefined;const to=target.clone().add(offset);if(instant||this.reduced){this.camera.position.copy(to);this.controls.target.copy(target);this.controls.update();}else this.cameraTween={from:this.camera.position.clone(),to,targetFrom:this.controls.target.clone(),targetTo:target,start:performance.now(),duration:1100};}
 photoView(id:string){const v=photoViews.find(v=>v.id===id);if(!v)return false;const place=places.find(p=>p.id===v.placeId),b=buildings.find(b=>b.id===place?.buildingIds[0]);if(!place||!b)return false;this.current=place;this.photoReference=id;this.dirty=true;this.cameraTween=undefined;this.controls.maxPolarAngle=Math.PI*.64;this.camera.fov=v.fov;this.camera.updateProjectionMatrix();const [x,z]=toWorld(b.position),[cx,cy,cz]=v.localCamera,[tx,ty,tz]=v.localTarget??[0,v.targetHeight,0],c=Math.cos(b.rotation),sn=Math.sin(b.rotation);this.camera.position.set(x+cx*c+cz*sn,cy,z-cx*sn+cz*c);this.controls.target.set(x+tx*c+tz*sn,ty,z-tx*sn+tz*c);this.controls.update();this.updateSelection(b);this.lastLabels=0;return true;}
 private exitPhotoView(){this.controls.autoRotate=false;if(!this.photoReference)return;this.photoReference=null;this.camera.fov=38;this.camera.updateProjectionMatrix();this.controls.maxPolarAngle=Math.PI*.43;}
 landmarkView(view:'tour'|'overview'|'north'|'south'|'east'|'west'|'top'|'front'|'back'){
  if(!this.current)return;const b=buildings.find(b=>b.id===this.current?.buildingIds[0]);if(!b)return;
  this.exitPhotoView();this.photoReference='landmark';this.controls.maxPolarAngle=Math.PI*.49;
  let [x,z]=toWorld(b.position);let size=Math.max(b.width,b.depth,b.height,30);if(this.current.id==='south-gate'){const c=Math.cos(b.rotation),s=Math.sin(b.rotation);x+=45*c-56*s;z+=-45*s-56*c;size=153;}if(this.current.id==='gym'){x+=24*Math.cos(b.rotation);z-=24*Math.sin(b.rotation);size=140;}const d=Math.max(100,size*2.8)*Math.max(1,.9/this.camera.aspect);
  const offsets={tour:[d*.7,d*.43,d*.7],overview:[d*.7,d*.8,d*.7],north:[0,d*.32,-d],south:[0,d*.32,d],east:[d,d*.32,0],west:[-d,d*.32,0],top:[0,d*1.3,.01],front:[Math.sin(b.rotation)*d,d*.24,Math.cos(b.rotation)*d],back:[-Math.sin(b.rotation)*d,d*.32,-Math.cos(b.rotation)*d]} as const;
  this.move(new T.Vector3(x,b.height*.4,z),new T.Vector3(...offsets[view]));
 }
 setOrbit(enabled:boolean){if(enabled&&!this.reduced&&this.controls.getPolarAngle()<.15)this.landmarkView('overview');this.controls.autoRotate=enabled&&!this.reduced;this.controls.autoRotateSpeed=.65;return this.controls.autoRotate;}
 captureView(){return [...this.camera.position.toArray(),...this.controls.target.toArray(),this.camera.fov].map(n=>Number(n.toFixed(2))).join(',');}
 restoreView(value:string){const a=value.split(',').map(Number);if(a.length!==7||a.some(n=>!Number.isFinite(n))||a.slice(0,6).some(n=>Math.abs(n)>4000)||a[1]<2.5||a[4]<0||a[4]>300||Math.abs(a[3])>850||Math.abs(a[5])>850||a[6]<20||a[6]>80)return false;this.cameraTween=undefined;this.controls.autoRotate=false;this.photoReference='shared';this.dirty=true;this.controls.maxPolarAngle=Math.PI*.64;this.camera.position.set(a[0],a[1],a[2]);this.controls.target.set(a[3],a[4],a[5]);this.camera.fov=a[6];this.camera.updateProjectionMatrix();this.controls.update();return true;}
 snapshot(){this.renderer.render(this.scene,this.camera);return this.renderer.domElement.toDataURL('image/png');}
 focus(id:string,instant=false){this.exitPhotoView();const p=places.find(p=>p.id===id);if(!p)return;this.current=p;const b=buildings.find(b=>b.id===p.buildingIds[0]);let [x,z]=toWorld(p.position);let size=Math.max(b?.width??60,b?.depth??60,b?.height??0);if(b&&id==='south-gate'){const c=Math.cos(b.rotation),s=Math.sin(b.rotation);x+=45*c-56*s;z+=-45*s-56*c;size=153;}if(b&&id==='gym'){x+=24*Math.cos(b.rotation);z-=24*Math.sin(b.rotation);size=140;}const distance=Math.max(190,size*3.2)*Math.max(1,.95/this.camera.aspect);this.move(new T.Vector3(x,0,z),new T.Vector3(distance*.65,distance*.9,distance*.5),instant);this.updateSelection(b);}
 private updateSelection(b?:typeof buildings[number]){this.dirty=true;disposeTree(this.selectedRing);this.selectedRing.clear();if(!b)return;const [x,z]=toWorld(b.position);const w=Math.max(b.width,20)+8,d=Math.max(b.depth,20)+8;const pts:Point[]=[[-w/2,-d/2],[w/2,-d/2],[w/2,d/2],[-w/2,d/2],[-w/2,-d/2]];const ring=pathMesh(pts,1.2,'#bd763e',1.3);ring.rotation.y=b.rotation;ring.position.x=x;ring.position.z=z;this.selectedRing.add(ring);}
 overview(instant=false,duration=1100){this.exitPhotoView();this.current=undefined;disposeTree(this.selectedRing);this.selectedRing.clear();this.viewArea='all';const scale=Math.max(1,1.35/this.camera.aspect);this.move(new T.Vector3(74,0,16),new T.Vector3(1062,1300,798).multiplyScalar(scale),instant);if(this.cameraTween)this.cameraTween.duration=duration;}
 area(area:Area,instant=false){this.exitPhotoView();this.current=undefined;disposeTree(this.selectedRing);this.selectedRing.clear();this.viewArea=area;const a=areas[area];const [x,z]=toWorld(a.center),d=a.distance*1.3*Math.max(1,1.1/this.camera.aspect);this.move(new T.Vector3(x,0,z),new T.Vector3(d*.65,d*.96,d*.49),instant);}
 top(){const t=this.controls.target.clone();const dist=this.viewArea==='all'?1300:areas[this.viewArea].distance*1.3;this.move(t,new T.Vector3(0,dist,.01));}
 north(){const d=this.camera.position.distanceTo(this.controls.target);this.move(this.controls.target.clone(),new T.Vector3(0,d*.8,d*.6));}
 zoom(mult:number){this.manual();const delta=this.camera.position.clone().sub(this.controls.target).multiplyScalar(mult);delta.setLength(T.MathUtils.clamp(delta.length(),65,3200));this.camera.position.copy(this.controls.target).add(delta);}
 filter(ids:Set<string>,planned:boolean){this.visibleIds=ids;this.planned.visible=planned;this.lastLabels=0;this.dirty=true;}
 trafficVisible(v:boolean){this.mobility.setVisible(v);this.dirty=true;}
 labelsVisible(v:boolean){this.showLabels=v;this.lastLabels=0;}
 lighting(mode:LightMode){
  this.lightMode=mode;this.dirty=true;const evening=mode==='sunset',glow=mode==='afterglow',night=mode==='night';
  this.nightLights.visible=night;this.mobility.setNight(night);for(const group of this.builtGroups.values())applyNightEmission(group,night);
  this.light.color.set(night?'#91aff0':glow?'#ffc28e':evening?'#ffbd7b':'#fff3d6');this.light.intensity=night?.65:glow?2.8:evening?2.7:3;
  this.light.position.set(night?-300:glow?-700:evening?-600:-400,night?650:glow?160:evening?270:800,500);
  this.roseRim.intensity=glow?1.1:0;this.hemi.color.set(night?'#7594c8':glow?'#b4a0d8':'#ddebf0');this.hemi.groundColor.set(night?'#263451':glow?'#a46b72':'#c1bd9c');this.hemi.intensity=night?.5:glow?1.35:evening?1.7:2.6;
  this.scene.background=night?this.nightSky:glow?this.sky:null;if(this.backdropGround)this.backdropGround.visible=!glow&&!night;
  this.renderer.toneMappingExposure=night?.9:glow?.88:.95;this.renderer.shadowMap.needsUpdate=true;
  const fog=night?'#14233c':glow?'#d8a0ae':evening?'#e9ded1':'#ecefe6';this.renderer.setClearColor(fog);this.scene.fog=new T.Fog(fog,glow||night?1200:1900,glow||night?2900:3300);
 }
 async exportModel(id='campus'){const {makeBuilding}=await import('./models');let input:T.Object3D;if(id==='campus'){const group=new T.Group();group.name='GDUT-University-Town';for(const b of buildings){if(places.find(p=>p.id===b.placeIds[0])?.status==='built')group.add(makeBuilding(b));}group.add(makeConnections());input=group;}else if(id==='south-gate'){const group=new T.Group(),anchor=buildings.find(b=>b.id==='b-admin')!,origin=toWorld(anchor.position);group.name='GDUT-South-Entrance-Ensemble';for(const key of ['b-admin','b-comprehensive','b-engineering-1','b-conference','b-south-gate','b-gdut-square']){const child=makeBuilding(buildings.find(b=>b.id===key)!);child.position.x-=origin[0];child.position.z-=origin[1];group.add(child);}group.rotation.y=-anchor.rotation;input=group;}else{const p=places.find(p=>p.id===id),b=buildings.find(b=>b.id===p?.buildingIds[0]);if(!b)throw new Error('未找到模型');input=makeBuilding(b);input.position.set(0,0,0);input.rotation.set(0,0,0);}const exporter=new GLTFExporter();let data:ArrayBuffer;try{data=await exporter.parseAsync(input,{binary:true,onlyVisible:true}) as ArrayBuffer;}finally{disposeTree(input);}const loaded=await new GLTFLoader().parseAsync(data,'');let meshes=0;loaded.scene.traverse(o=>{if(o instanceof T.Mesh)meshes++;});disposeTree(loaded.scene);if(!meshes)throw new Error('模型导出为空');return {data,meshes};}
 dispose(){this.sky.dispose();this.nightSky.dispose();this.disposed=true;cancelAnimationFrame(this.raf);this.resizeObs.disconnect();this.controls.dispose();this.renderer.domElement.removeEventListener('pointerdown',this.onDown);this.renderer.domElement.removeEventListener('pointerup',this.onUp);this.renderer.domElement.removeEventListener('keydown',this.onKey);this.renderer.domElement.removeEventListener('webglcontextlost',this.onLost);disposeTree(this.scene);this.pickers.forEach(p=>{p.geometry.dispose();(p.material as T.Material).dispose();});this.renderer.dispose();this.renderer.domElement.remove();this.labelHost.replaceChildren();}
}
export {tourIds};

